apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dftb1zbsp-go 
  janus-idp.io/tekton: dftb1zbsp-go
  backstage.io/kubernetes-id: dftb1zbsp-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dftb1zbsp-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml